// AgentResults — v2 nuclear rebuild.  Route: /reports/:runId
//
// The signature page of the app.  The verdict moment that has to look like
// it was art-directed for a magazine cover, not generated by a SaaS template.
//
// Three spreads.  No more.
//   A · Verdict     ivory, full-bleed, 80vh, 96px Figtree 900 headline +
//                   hand-drawn red-orange squiggle under "Rewrite" +
//                   receipt mascot standing on the right margin.
//   B · Findings    canvas, three plain ink-bordered cards, no tilt.
//   C · Anatomy     canvas, full-bleed, stylised ink-framed page preview
//                   with three red-orange numbered marker pins and dashed
//                   leader lines.  ONE Caveat margin note.  ONE tilted frame.
//
// Discipline rules (locked, page-level):
//   1 · 5 font sizes total — 96 (display) / 32 (H2) / 17 (body) / 14 (mono) / 32 hand (Caveat).
//   2 · One tilted element on the page — the annotated preview frame in C.
//   3 · One mascot — receipt pose in Spread A.
//   4 · One Caveat — "generic platform copy" in Spread C.
//   5 · Three spreads. Verdict / Findings / Anatomy.
//
// Allowed lifts:
//   - after-click/aurora.html "Find where paid clicks die" block (parent design).
//   - The verdict-page conventions in AFTER-CLICK-HTML-BRAND-GUIDELINES.md.

import type { CSSProperties } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Caveat } from '../components/brand/Caveat';
import { Mascot } from '../components/brand/Mascot';
import { PillButton } from '../components/brand/PillButton';
import { RUNS } from '../mock/runs';

// ─── HELPERS ──────────────────────────────────────────────────────────────

// Three fabricated findings for the Findings spread.  Plain ink-bordered
// cards; the marker pins on Spread C correspond 01/02/03 to these.
type FindingCard = { number: string; headline: string; body: string };

const FINDINGS: FindingCard[] = [
  {
    number: '01',
    headline: "Headline doesn't match the ad.",
    body:
      'The ad promised "same-day case review" but the page leads with a generic firm bio. Every paid click reads it as a bait-and-switch in the first 400ms.',
  },
  {
    number: '02',
    headline: 'Three CTAs compete above the fold.',
    body:
      '"Get a quote", "Schedule a call", and a chat widget all fire on first paint. Visitors spend their decision budget choosing between them instead of clicking.',
  },
  {
    number: '03',
    headline: 'Pricing buried behind a click.',
    body:
      'The single highest-intent question on the page — "what does this cost" — sits four scrolls down. Three rivals lead with a price band in the hero.',
  },
];

// Hand-drawn red-orange squiggle.  ~440px wide, 18px tall.  Two overlapping
// wavy paths give it the "drawn twice with a marker" feel — Stewart's brand
// hand-annotation is rarely a single perfect line.
function SquiggleUnderline({ className = '' }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 440 18"
      className={className}
      width="440"
      height="18"
      fill="none"
      aria-hidden="true"
    >
      <path
        d="M 4 11 C 36 2, 74 17, 110 9 S 184 2, 222 11 S 296 17, 332 9 S 408 2, 436 11"
        stroke="#F24A2E"
        strokeWidth="4"
        strokeLinecap="round"
      />
      <path
        d="M 6 13 C 38 4, 76 16, 112 11 S 186 4, 224 13"
        stroke="#F24A2E"
        strokeWidth="2.5"
        strokeLinecap="round"
        opacity="0.55"
      />
    </svg>
  );
}

// A single marker pin.  Red-orange circle, white "01" / "02" / "03" inside.
// Positioned absolutely by the caller.  Includes an optional dashed leader
// line — caller passes the line endpoints.
function MarkerPin({
  number,
  style,
}: {
  number: string;
  style: CSSProperties;
}) {
  return (
    <div
      style={style}
      className="absolute z-10 grid place-items-center rounded-full border-[2px] border-ink bg-redorange text-white font-display text-[20px] font-black leading-none shadow-btn"
      // 40px square pin.
      // Inline width/height to keep this self-contained without arbitrary
      // class noise.
    >
      <span className="-mt-px">{number}</span>
    </div>
  );
}

// A single dashed leader line.  Inline SVG positioned absolutely so it
// scales with the preview frame.  Each line goes pin → trouble spot.
function LeaderLine({
  x1, y1, x2, y2, style,
}: {
  x1: number; y1: number; x2: number; y2: number; style?: CSSProperties;
}) {
  return (
    <svg
      style={style}
      className="pointer-events-none absolute inset-0 h-full w-full"
      viewBox="0 0 100 100"
      preserveAspectRatio="none"
      aria-hidden="true"
    >
      <line
        x1={x1}
        y1={y1}
        x2={x2}
        y2={y2}
        stroke="#F24A2E"
        strokeWidth="0.4"
        strokeDasharray="1.2 1.2"
        strokeLinecap="round"
        vectorEffect="non-scaling-stroke"
      />
    </svg>
  );
}

// ─── PAGE ─────────────────────────────────────────────────────────────────

export function AgentResults() {
  const { runId } = useParams<{ runId: string }>();
  const run = runId ? RUNS[runId] : undefined;

  if (!run) {
    return (
      <div className="grid min-h-[60vh] place-items-center bg-ivory px-6 font-sans text-ink">
        <div className="text-center">
          <h1 className="font-display text-[48px] font-black leading-[0.95] tracking-[-0.025em]">
            Report not found.
          </h1>
          <p className="mt-4 text-[17px] text-ink/70">
            We couldn't locate run <span className="font-mono text-[14px]">{runId}</span>.
          </p>
          <div className="mt-8">
            <Link to="/reports">
              <PillButton variant="ghost">Back to all reports</PillButton>
            </Link>
          </div>
        </div>
      </div>
    );
  }

  // Pull the bits we use from the run.  Date is hardcoded to the brief
  // ("2026-05-14") because mock data doesn't carry a finish timestamp.
  const agentSlug = run.agentSlug;          // "competitor-spy"
  const projectId = run.projectId;          // "boulder-care" — used as the line below buttons
  const dateLabel = '2026-05-14';
  const metaLine = `${agentSlug} · ${projectId} · ${dateLabel}`;

  return (
    <div className="text-ink">
      {/* ════════════════════════════════════════════════════════════════
          SPREAD A · VERDICT
          Ivory canvas, full-bleed, ~80vh.  96px display headline with the
          word "Rewrite" annotated by a hand-drawn red-orange squiggle.
          Receipt mascot on the right margin.  CTA pills + mono meta line.
          ════════════════════════════════════════════════════════════════ */}
      <section className="relative bg-ivory">
        <div className="mx-auto grid min-h-[80vh] max-w-[1280px] grid-cols-1 items-center gap-12 px-6 py-20 md:grid-cols-[1fr_280px] md:gap-16 md:px-12 md:py-28">
          {/* Headline column */}
          <div className="relative">
            {/* Verdict headline.  Three ragged-right lines.  The squiggle
                lives inside the first line, absolutely positioned under
                the word "Rewrite". */}
            <h1
              className="font-display font-black text-ink"
              style={{
                lineHeight: 0.92,
                letterSpacing: '-0.035em',
              }}
            >
              {/* Line 1 — holds the annotated word */}
              <span className="relative inline-block text-[48px] md:text-[96px]">
                <span className="relative inline-block">
                  Rewrite
                  {/* Hand-drawn squiggle, anchored to the bottom of the word */}
                  <SquiggleUnderline className="absolute left-0 -bottom-3 w-[100%] md:-bottom-4 md:w-[110%]" />
                </span>{' '}
                the first screen
              </span>
              <br />
              <span className="text-[48px] md:text-[96px]">before scaling</span>
              <br />
              <span className="text-[48px] md:text-[96px]">paid spend.</span>
            </h1>

            {/* CTAs + mono meta */}
            <div className="mt-12 flex flex-wrap items-center gap-4 md:mt-16">
              <PillButton variant="primary" href="#rebuild">
                Open the rebuild →
              </PillButton>
              <PillButton variant="ghost">Export PDF</PillButton>
            </div>
            <p className="mt-5 font-mono text-[14px] uppercase tracking-[0.06em] text-ink/60">
              {metaLine}
            </p>
          </div>

          {/* Mascot column — desktop only as a true right-margin standee.
              On mobile the mascot stacks under the meta line at 160px. */}
          <div className="hidden md:block">
            <Mascot pose="receipt" size={240} className="ml-auto block" />
          </div>
          <div className="md:hidden">
            <Mascot pose="receipt" size={160} />
          </div>
        </div>
      </section>

      {/* ════════════════════════════════════════════════════════════════
          SPREAD B · FINDINGS
          Canvas.  H2 32px, three plain ink-bordered cards.  No tilt, no
          eyebrows, no chips.  The numbers 01/02/03 are repeated on the
          Spread C marker pins.
          ════════════════════════════════════════════════════════════════ */}
      <section className="bg-ppc-canvas">
        <div className="mx-auto max-w-[1280px] px-6 py-24 md:px-12 md:py-28">
          <h2
            className="font-display font-extrabold text-ink"
            style={{
              fontSize: '32px',
              lineHeight: 1.05,
              letterSpacing: '-0.02em',
            }}
          >
            What we found.
          </h2>

          <div className="mt-12 grid grid-cols-1 gap-8 md:grid-cols-3">
            {FINDINGS.map((f) => (
              <article
                key={f.number}
                className="flex flex-col rounded-2xl border-[2px] border-ink bg-white p-8"
              >
                {/* Number — mono 14px, the one place mono earns its keep on
                    this page besides the meta line in Spread A. */}
                <span className="font-mono text-[14px] uppercase tracking-[0.06em] text-redorange">
                  {f.number}
                </span>

                {/* Card headline.  H2-sized so the page only has 4 type
                    sizes in regular use (96 / 32 / 17 / 14). */}
                <h3
                  className="mt-4 font-display font-extrabold text-ink"
                  style={{
                    fontSize: '32px',
                    lineHeight: 1.05,
                    letterSpacing: '-0.02em',
                  }}
                >
                  {f.headline}
                </h3>

                <p
                  className="mt-4 flex-1 text-[17px] leading-[1.55]"
                  style={{ color: 'rgba(15, 10, 30, 0.75)' }}
                >
                  {f.body}
                </p>

                <div className="mt-8">
                  <PillButton variant="ghost" href={`#pin-${f.number}`}>
                    See in page →
                  </PillButton>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* ════════════════════════════════════════════════════════════════
          SPREAD C · ANATOMY
          The after.click homage.  Stylised page screenshot in an
          ink-bordered frame (THE one tilted element on the page).  Three
          numbered marker pins with dashed leader lines.  One Caveat
          margin note pointing at the worst offender.
          ════════════════════════════════════════════════════════════════ */}
      <section className="bg-ppc-canvas">
        <div className="mx-auto max-w-[1280px] px-6 pb-28 md:px-12 md:pb-32">
          <h2
            className="font-display font-extrabold text-ink"
            style={{
              fontSize: '32px',
              lineHeight: 1.05,
              letterSpacing: '-0.02em',
            }}
          >
            Where paid clicks die.
          </h2>

          {/* Annotated preview region.  Outer wrapper is the positioning
              context for the pins, leader lines, and Caveat — they sit
              relative to the FRAME, not the preview content. */}
          <div className="relative mt-12">
            {/* The tilted frame.  This is the page's ONE tilted element.
                On mobile we drop the tilt so the marker pins stay legible. */}
            <div
              className="relative mx-auto aspect-[4/3] w-full max-w-[960px] rounded-xl border-[2px] border-ink bg-white shadow-sticker md:rotate-[1deg]"
            >
              {/* ── Stylised "page screenshot" composition ──────────────
                  The site we're auditing, as flat ink shapes.  Header bar,
                  hero image area, two stacked CTAs, a content rail, a
                  pricing teaser at the bottom.  Designed so the three
                  pins have something obvious to point at. */}

              {/* Header bar */}
              <div className="absolute left-0 right-0 top-0 flex h-12 items-center gap-2 border-b border-ink/10 px-5">
                <div className="h-3 w-3 rounded-full bg-ink/30" />
                <div className="ml-2 h-2 w-24 rounded bg-ink/15" />
                <div className="ml-auto flex gap-3">
                  <div className="h-2 w-12 rounded bg-ink/10" />
                  <div className="h-2 w-12 rounded bg-ink/10" />
                  <div className="h-2 w-12 rounded bg-ink/10" />
                </div>
              </div>

              {/* Body padding starts below the header */}
              <div className="absolute inset-x-0 top-12 bottom-0 px-8 py-7">
                {/* PIN 01 target — page hero headline mismatch */}
                <div className="space-y-3">
                  {/* Hero "headline" — mismatched, doesn't match the ad.
                      This is what Pin 01 points at. */}
                  <div className="h-5 w-2/3 rounded bg-ink/65" id="anatomy-headline" />
                  <div className="h-3 w-1/2 rounded bg-ink/20" />
                </div>

                {/* Hero image placeholder */}
                <div className="mt-5 h-32 w-full rounded-lg bg-ink/12" />

                {/* PIN 02 target — three competing CTAs.  We render three
                    pill-shaped blocks in a row, which is exactly the bug
                    being called out. */}
                <div className="mt-5 flex items-center gap-3" id="anatomy-ctas">
                  <div className="h-7 w-28 rounded-full bg-ink/75" />
                  <div className="h-7 w-32 rounded-full border border-ink/40" />
                  <div className="h-7 w-24 rounded-full border border-ink/40" />
                </div>

                {/* Content rail — generic blocks */}
                <div className="mt-5 space-y-2">
                  <div className="h-2 w-3/4 rounded bg-ink/10" />
                  <div className="h-2 w-2/3 rounded bg-ink/10" />
                  <div className="h-2 w-1/2 rounded bg-ink/10" />
                </div>

                {/* PIN 03 target — pricing teaser at the bottom.  This is
                    what Pin 03 (pricing buried) points at. */}
                <div
                  className="absolute inset-x-8 bottom-6 flex items-center justify-between rounded-md border border-ink/20 px-4 py-3"
                  id="anatomy-pricing"
                >
                  <div className="h-2 w-24 rounded bg-ink/25" />
                  <div className="h-3 w-16 rounded bg-ink/15" />
                </div>
              </div>

              {/* ── Marker pins ──────────────────────────────────────────
                  Pins live INSIDE the tilted frame so they tilt with it.
                  Positions are anchored to the trouble spots above. */}
              <MarkerPin
                number="01"
                style={{
                  width: 40,
                  height: 40,
                  // Up-left of the frame, near the mismatched headline
                  top: '14%',
                  left: '-20px',
                }}
              />
              <MarkerPin
                number="02"
                style={{
                  width: 40,
                  height: 40,
                  // Right side, level with the three-CTA row
                  top: '58%',
                  right: '-20px',
                }}
              />
              <MarkerPin
                number="03"
                style={{
                  width: 40,
                  height: 40,
                  // Below the pricing strip
                  bottom: '-20px',
                  left: '52%',
                }}
              />

              {/* ── Dashed leader lines ──────────────────────────────────
                  Each line connects a pin's "page edge" to its trouble
                  spot.  Coordinate space is 0-100 of the frame. */}
              <LeaderLine x1={2} y1={17} x2={26} y2={22} />
              <LeaderLine x1={98} y1={60} x2={62} y2={55} />
              <LeaderLine x1={55} y1={98} x2={50} y2={88} />
            </div>

            {/* Caveat — the one allowed hand-note on the page.  Points
                down-left toward Pin 01 (the worst offender / mismatched
                headline).  Positioned in the right margin of the frame
                on desktop, dropped under the frame on mobile. */}
            <div className="mt-8 flex justify-center md:absolute md:right-0 md:top-12 md:mt-0 md:max-w-[220px] md:justify-end">
              <Caveat arrow="down-left" text="generic platform copy" />
            </div>
          </div>

        </div>
      </section>
    </div>
  );
}
